version: "3.3"
services:
  db:
    image: postgres
    depends_on:
      - web
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: foggyoon/krikey-node-app
    ports:
      - "3000:3000"

